# Generated by Django 6.0.7 on 2026-07-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_treinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='treino',
            name='calorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treino',
            name='ritmo_medio',
            field=models.CharField(default="0'00''", max_length=20),
        ),
        migrations.AddField(
            model_name='treino',
            name='zona_predominante',
            field=models.CharField(default='Aeróbico', max_length=50),
        ),
        migrations.AlterField(
            model_name='treino',
            name='distancia_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='treino',
            name='tempo_minutos',
            field=models.IntegerField(),
        ),
    ]
