# Generated by Django 6.0.7 on 2026-07-20 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_treinos', '0002_rename_user_treino_usuario_treino_calorias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='zona_predominante',
            field=models.CharField(choices=[('Z1', 'Zona 1 - Recuperação'), ('Z2', 'Zona 2 - Aeróbico / Base'), ('Z3', 'Zona 3 - Limiar / Tempo'), ('Z4', 'Zona 4 - VO2 Máximo'), ('Z5', 'Zona 5 - Anaeróbico')], default='Z2', max_length=2, verbose_name='Zona Cardíaca Predominante'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atleta', 'Atleta / Paciente'), ('medico', 'Médico / Cardiologista'), ('fisio', 'Fisioterapeuta / Ortopedista'), ('nutri', 'Endocrinologista / Nutricionista')], default='atleta', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescricaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limite', models.DateField()),
                ('descricao_meta', models.TextField(help_text="Ex: Correr 5km abaixo de 5'30'' com foco aeróbico.")),
                ('concluido', models.BooleanField(default=False)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
