# Generated by Django 6.0.7 on 2026-07-26 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_treinos', '0003_alter_treino_zona_predominante_perfilusuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('atleta', 'Atleta / Aluno'), ('treinador', 'Treinador / Educador'), ('medico', 'Médico / Profissional de Saúde')], default='atleta', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescricaotreino',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Atleta'),
        ),
        migrations.AlterField(
            model_name='prescricaotreino',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='prescricaotreino',
            name='data_limite',
            field=models.DateField(verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='prescricaotreino',
            name='descricao_meta',
            field=models.TextField(verbose_name='Descrição da Meta / Prescrição'),
        ),
        migrations.AlterField(
            model_name='prescricaotreino',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='calorias',
            field=models.IntegerField(default=0, verbose_name='Calorias (kcal)'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_treino',
            field=models.DateField(verbose_name='Data do Treino'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='ritmo_medio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ritmo Médio'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='tempo_minutos',
            field=models.IntegerField(verbose_name='Tempo (minutos)'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='zona_predominante',
            field=models.CharField(blank=True, choices=[('Z1', 'Zona 1 - Recuperação'), ('Z2', 'Zona 2 - Aeróbico / Base'), ('Z3', 'Zona 3 - Limiar / Tempo'), ('Z4', 'Zona 4 - VO2 Máximo'), ('Z5', 'Zona 5 - Anaeróbico')], max_length=2, null=True, verbose_name='Zona Cardíaca Predominante'),
        ),
    ]
