# Generated by Django 6.0.7 on 2026-07-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_treinos', '0004_alter_perfilusuario_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='tempo_minutos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo (minutos)'),
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='gestao_treinos.treino')),
            ],
        ),
    ]
