# Generated by Django 5.1.2 on 2026-08-02 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_treinos', '0005_alter_treino_distancia_km_alter_treino_tempo_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.TextField(default='Sem detalhes')),
            ],
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prescricaotreino',
            name='atleta',
        ),
        migrations.RemoveField(
            model_name='prescricaotreino',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='ritmo_medio',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='zona_predominante',
        ),
        migrations.AddField(
            model_name='treino',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_treino',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='treino',
            name='tempo_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Coordenada',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.DeleteModel(
            name='PrescricaoTreino',
        ),
    ]
