# Generated by Django 5.1.2 on 2026-08-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_treinos', '0006_prescricao_remove_perfilusuario_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='prescricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_treinos.prescricao'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_treino',
            field=models.DateField(auto_now_add=True),
        ),
    ]
